name: Action Demo

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - main
  schedule:
    # Runs at 06:15 UTC on Sunday
    - cron: '15 6 * * 0'
  workflow_dispatch:
    # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Run build process
        run: echo "Building a cat"
        
      - name: Run tests
        run: echo "OIIA OIIA"
