name: Action Demo

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - main
  schedule:
    # Runs at 06:15 UTC on Sunday
    - cron: '15 6 * * 0'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Cat to pet'
        type: environment
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Run build process
        run: echo "Building a cat"
        
      - name: Run tests
        run: echo "OIIA OIIA"
  
  Feed-cat:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch'
    environment: Feed-cat
    steps:
      - name: Feed
        run: echo "Feeding..."
  
  Pet-cat:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch'
    environment: Pet-cat
    steps:
      - name: Pet
        run: echo "Petting..."
      - name: Wait
        run: sleep 15
  
  Release-cat:
    runs-on: ubuntu-latest
    needs: [Feed-cat, Pet-cat]
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'Release-cat'
    environment:
      name: Release-cat
      url: https://writeabout.net
    steps:
      - name: Step 1
        run: |
          echo "Step 1 deploying..."
          sleep 10
      
      - name: Step 2
        run: |
          echo "Step 2 deploying..."
          sleep 10
      
      - name: Step 3
        run: |
          echo "Step 3 deploying..."
          sleep 10
      
      - name: Step 4
        run: |
          echo "Step 4 deploying..."
          sleep 10
      
      - name: Step 5
        run: |
          echo "Step 5 deploying..."
          sleep 10
