name: Resuable working cat
on:
  workflow_call:
    inputs:
      who-to-greet:
        description: 'cat owner'
        default: 'apang'
        type: string
        required: true
    outputs:
      current-time:
        description: 'The current time when the cat meow'
        value: ${{ jobs.reusable-job.outputs.current-time }}

jobs:
  reusable-job:
    runs-on: ubuntu-latest
    outputs:
      current-time: ${{ steps.time.outputs.time }}
    steps:
      - name: Meow
        run: echo "OIIAI OIIAI, ${{ inputs.who-to-greet }}"

      - name: Set time
        id: time
        run: echo "time=$(date)" >> $GITHUB_OUTPUT

    
    
